#!/usr/bin/env bash
# Builds the helmet equipment pictures end to end:
#   1. Resizes every PNG under gfx/interface/STH_equipment_pictures/helmets/
#      to a fixed TARGET_WIDTH x TARGET_HEIGHT canvas, in place. Aspect
#      ratio is preserved (no stretching) - the image is scaled to fit
#      within the canvas, then centered on a fully transparent background
#      to fill out the rest.
#   2. Converts each (now fixed-size) PNG to DDS in place via todds
#      (foo.png -> foo.dds, same name/folder). BC3 (block compression)
#      hard-requires both dimensions to be multiples of 4, and 54 isn't -
#      so the DDS file's own header will report 56, not 54 (--fix-size
#      rounds up rather than crashing on encode). The extra 2px is fully
#      transparent padding centered by step 1, so it's not visible in
#      game - there is no way to get an exact 164x54 *and* use a
#      block-compressed DDS format; the rounding is mandatory for BC3.
#      Mipmaps are left enabled (no --no-mipmaps) because todds 0.4.1 has
#      a known crash when --no-mipmaps is combined with --fix-size on a
#      non-multiple-of-4 source - mipmaps are unused/harmless extra data
#      for a static UI icon anyway.
#   3. Regenerates interface/replace/STH_Helmet_Equipment_Pictures.gfx by
#      scanning that same folder for *.dds files.
#
# Run this any time you add, replace, remove, or rename files under that
# folder - the resize, the DDS conversion, and the .gfx file are all fully
# derived from what's on disk, so none of them need to be hand-edited.
set -euo pipefail

TARGET_WIDTH=164
TARGET_HEIGHT=54

MOD_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELMETS_DIR="$MOD_ROOT/gfx/interface/STH_equipment_pictures/helmets"
OUT_FILE="$MOD_ROOT/interface/replace/STH_Helmet_Equipment_Pictures.gfx"

if [ ! -d "$HELMETS_DIR" ]; then
    echo "No helmet picture folder found at: $HELMETS_DIR" >&2
    exit 1
fi

# --- Step 1: resize/pad PNGs to a fixed canvas, then convert to DDS ---

shopt -s nullglob globstar
pngs=("$HELMETS_DIR"/**/*.png)
shopt -u nullglob globstar

if [ ${#pngs[@]} -eq 0 ]; then
    echo "No PNG files found under $HELMETS_DIR - skipping conversion."
else
    if ! command -v magick >/dev/null 2>&1; then
        echo "ImageMagick (magick) not found on PATH - install it to enable resizing." >&2
        exit 1
    fi
    if ! command -v todds >/dev/null 2>&1; then
        echo "todds not found on PATH - install it from https://github.com/joaodicastro/todds" >&2
        exit 1
    fi

    for f in "${pngs[@]}"; do
        magick "$f" \
            -resize "${TARGET_WIDTH}x${TARGET_HEIGHT}" \
            -background none \
            -gravity center \
            -extent "${TARGET_WIDTH}x${TARGET_HEIGHT}" \
            "$f"
    done
    echo "Resized ${#pngs[@]} PNG file(s) to ${TARGET_WIDTH}x${TARGET_HEIGHT}."

    todds \
        --format BC3 \
        --fix-size \
        --overwrite \
        --progress \
        "$HELMETS_DIR"

    echo "Converted ${#pngs[@]} PNG file(s) under $HELMETS_DIR to DDS."
fi

# --- Step 2: regenerate the .gfx file from whatever .dds files exist now ---

{
    echo "# Auto-generated by generate_helmet_pictures_gfx.sh - do not hand-edit."
    echo "# Re-run that script after adding/removing/renaming files under"
    echo "# gfx/interface/STH_equipment_pictures/helmets/ to regenerate this file."
    echo "spriteTypes = {"

    for dir in "$HELMETS_DIR"/*/; do
        [ -d "$dir" ] || continue
        suffix="$(basename "$dir")"

        shopt -s nullglob
        files=("$dir"*.dds)
        shopt -u nullglob
        [ ${#files[@]} -eq 0 ] && continue

        sorted=()
        while IFS= read -r line; do
            sorted+=("$line")
        done < <(printf '%s\n' "${files[@]}" | sort)

        echo ""
        echo -e "\t# --- helmet_equipment_${suffix} ---"

        for f in "${sorted[@]}"; do
            fname="$(basename "$f")"
            name_no_ext="${fname%.dds}"
            rel_path="gfx/interface/STH_equipment_pictures/helmets/${suffix}/${fname}"
            echo -e "\tSpriteType = {"
            echo -e "\t\tname = \"GFX_STH_helmet_equipment_${name_no_ext}\""
            echo -e "\t\ttexturefile = \"${rel_path}\""
            echo -e "\t}"
        done
    done

    echo ""
    echo "}"
} > "$OUT_FILE"

count=$(grep -c "SpriteType = {" "$OUT_FILE")
echo "Wrote $count SpriteType entries to $OUT_FILE"
